# fly.toml app configuration file generated for rogue-scholar-api on 2023-10-03T12:56:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rogue-scholar-api"
primary_region = "ams"

[deploy]
  strategy = "rolling"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
