name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        run: tox -e py311
        env:
          QUART_SUPABASE_URL: ${{ secrets.QUART_SUPABASE_URL }}
          QUART_SUPABASE_ANON_KEY: ${{ secrets.QUART_SUPABASE_ANON_KEY }}
          QUART_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.QUART_SUPABASE_SERVICE_ROLE_KEY }}
          QUART_TYPESENSE_API_KEY: ${{ secrets.QUART_TYPESENSE_API_KEY }}
          QUART_TYPESENSE_HOST: ${{ secrets.QUART_TYPESENSE_HOST }}
          QUART_SENTRY_DSN: ${{ secrets.QUART_SENTRY_DSN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}